language: bash
services: docker

env:
  - TAG=7.3-fpm-stretch 
  - TAG=7.3.11-fpm-stretch 
  - TAG=7.2.19-fpm-stretch 
  - TAG=7.2.24-fpm-stretch 
  - TAG=7.2-fpm-stretch 
  - TAG=7.1-fpm-stretch 
  - TAG=7.0-fpm-stretch 

install:
  - echo "skip"

before_script:
  - env | sort
  - image="${DOCKER_REPO}:${TAG}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" --build-arg IMAGE_TAG=${TAG} .
    )
after_script:
  - docker images

deploy:
- provider: script
  script: >- 
   docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
   && docker push $image
