language: bash
group: stable
dist: trusty
os: linux
services:
- docker
install:
    - echo "skipping tests"

script:
    - echo "skipping tests"

before_deploy: |-
    # Generate image tags
    export build_tag="pristtlt/lnp-base:${TRAVIS_TAG}"

    # Build docker image
    docker build \
    -t ${build_tag} \
    .

deploy:
- provider: script
  script:  >-
    docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
    && docker push ${build_tag}
  skip_cleanup: true
  on:
    all_branches: true