if: branch =~ ^master$|^test
language: bash
services: docker

env:
  - OFFICIAL_TAG=7.3-fpm-stretch SWOOLE_VERSION=4.4.12
  - OFFICIAL_TAG=7.2-fpm-stretch SWOOLE_VERSION=4.4.12
  - OFFICIAL_TAG=7.1-fpm-stretch SWOOLE_VERSION=4.4.12
  - OFFICIAL_TAG=7.0-fpm-stretch SWOOLE_VERSION=2.2.0

install:
  - echo "skip"

before_script:
  - env | sort

script: |-
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    export image_tags=(
      # example: 7.3-fpm-stretch
      "${DOCKER_REPO}:${OFFICIAL_TAG}"
    )
  else
    export image_tags=(
      # example: 7.3-fpm-stretch-xx-dev
      "${DOCKER_REPO}:${OFFICIAL_TAG}-${TRAVIS_BUILD_NUMBER}-dev"
    )
  fi

  for tag in ${image_tags[@]};
  do
    docker build -t $tag --build-arg IMAGE_TAG=${OFFICIAL_TAG} --build-arg swoole_version=${SWOOLE_VERSION} .
  done

after_script:
  - docker images

deploy:
- provider: script
  script: >- 
   docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
   && for tag in ${image_tags[@]}; do docker push -t $tag; done
  on:
    branch: 
    - master
