if: branch =~ ^master$|^test
language: bash
services: docker

env:
  - OFFICIAL_TAG=7.3.12-fpm-stretch SECOND_TAG=v0.2 SWOOLE_VERSION=4.4.12
  - OFFICIAL_TAG=7.2.25-fpm-stretch SECOND_TAG=v0.2 SWOOLE_VERSION=4.4.12
  - OFFICIAL_TAG=7.1.33-fpm-stretch SECOND_TAG=v0.2 SWOOLE_VERSION=4.4.12
  # php 7.0 newest swoole version is 2.2.0
  - OFFICIAL_TAG=7.0.33-fpm-stretch SECOND_TAG=v0.2 SWOOLE_VERSION=2.2.0

install:
  - echo "skip"

before_script:
  - env | sort

script: |-
  set -e

  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    export image_tags=(
      # example: 7.3-fpm-stretch
      "${DOCKER_REPO}:${OFFICIAL_TAG%.*}-${OFFICIAL_TAG#*-}"
      # example: 7.3.12-fpm-stretch
      "${DOCKER_REPO}:${OFFICIAL_TAG}"
      # example: 7.3.12-fpm-stretch-v0.1
      "${DOCKER_REPO}:${OFFICIAL_TAG}-${SECOND_TAG}"
      # example: 7.3.12-fpm-stretch-v0.1.xx
      "${DOCKER_REPO}:${OFFICIAL_TAG}-${SECOND_TAG}.${TRAVIS_BUILD_NUMBER}"
    )

    export deploy_script="docker push ${image_tags[0]} && docker push ${image_tags[1]} && docker push ${image_tags[2]}"
    # echo $DEPLOY_SCRIPT
  else
    export image_tags=(
      # example: 7.3.12-fpm-stretch-v0.1.xx-dev
      "${DOCKER_REPO}:${OFFICIAL_TAG}-${SECOND_TAG}.${TRAVIS_BUILD_NUMBER}-dev"
    )

    export deploy_script="docker push ${image_tags[0]}"
    # echo $DEPLOY_SCRIPT;
  fi

  for tag in ${image_tags[@]};
  do
    docker build -t $tag --build-arg IMAGE_TAG=${OFFICIAL_TAG} --build-arg SWOOLE_VERSION=${SWOOLE_VERSION} .
  done

after_script:
  - docker images

deploy:
- provider: script
  script: >-
    docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
    && ${deploy_script}
  on:
    all_branches: true
